hsurf17 = uicontrol('Style','pushbutton',...
    'String','Here for the cake?','Position',[480,200,250,40], ...
    'Callback','lieCAKE', ...
    'Fontsize',15,'ForegroundColor','green');

Launch = importdata('launch3.jpg');
set(hsurf17 ,'CDATA',Launch);