hsurf7 = uicontrol('Style','pushbutton',...
    'String','Level 1','Position',[480,300,250,40], ...
    'Callback','Level1', ...
    'Fontsize',15,'ForegroundColor','green');

hsurf8 = uicontrol('Style','pushbutton',...
    'String','Level 2','Position',[480,250,250,40], ...
    'Callback','Level2', ...
    'Fontsize',15,'ForegroundColor','green');

hsurf9 = uicontrol('Style','pushbutton',...
    'String','Level 3','Position',[480,200,250,40], ...
    'Callback','Level3', ...
    'Fontsize',15,'ForegroundColor','green');

set(hsurf7 ,'CDATA',Launch);
set(hsurf8 ,'CDATA',Launch);
set(hsurf9 ,'CDATA',Launch);